### ISSUE TITLE
Feature: Edit/View .desktop entries in /usr/share/xsessions

### ISSUE THREAD

**Issue by rfebbo** [gdm-settings/gdm-settings#166]
### Description

Another customization feature for GDM. This would change the list of options in the cog gear in the bottom right when you are typing in your password. This can allow different sessions such as wayland sessions

**Comment by realmazharhussain** [comment]
Session files are installed by each session according to what they support. For example gnome-session installs

```
/usr/share/wayland-sessions/gnome.desktop
/usr/share/xsessions/gnome.desktop
/usr/share/xsessions/gnome-xorg.desktop
```

To indicate that gnome-session supports both Wayland and XOrg.

Messing with those files seems like a bad idea.

However, I was unable to use a GNOME Wayland session on Kali Linux because they disable Wayland for GDM itself. You could be having a similar issue.

Please, describe the issue you are having in more details and also provide information about the system on which you are experiencing the issue. So that it can be resolved properly. You can even use the "Bug Report" issue template, which will guide you on what information to provide.

**Comment by rfebbo** [comment]
OK, I see. Thank you!
