### ISSUE TITLE
Please migrate to GNOME 44 runtime (or, better still, 45)

### ISSUE THREAD

**Issue by xpseudonym** [gdm-settings/gdm-settings#197]
### What happened?

```
$ flatpak update
Looking for updates…
Info: org.gnome.Platform//43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.realmazharhussain.GdmSettings
Nothing to do.
$
```

### Expected behavior

```
$ flatpak update
Looking for updates…
Nothing to do.
$
```

### To Reproduce

`$ flatpak update`

### Detailed Explanation (Optional)

As above.

### Application Version

3.alpha.0

### Format/Source

Flatpak

### Environment

- **OS**:  PureOS 10 (Byzantium) - Debian derivative
- **GNOME**:  3.38.5

**Comment by realmazharhussain** [comment]
The latest version of GDM Settings is 3.3 and it uses GNOME 45 runtime. I think you might be using testing or master branch of the flatpak stuck at v3.alpha.0 since those branches don't have any upgrade path.

Install the latest stable release to fix the issue.

```bash
flatpak install io.github.realmazharhussain.GdmSettings//stable
```

You can safely uninstall the offending branch.

```bash
flatpak uninstall io.github.realmazharhussain.GdmSettings//master
flatpak uninstall io.github.realmazharhussain.GdmSettings//testing
```

**Comment by xpseudonym** [comment]
Many thanks for the information
