### ISSUE TITLE
Have an option to automatically set the desktop wallpaper as the lockscreen wallpaper

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [gdm-settings/gdm-settings#201]
### Description

title

**Comment by realmazharhussain** [comment]
First of all, I think you mean the login screen wallpaper not "lockscreen wallpaper".

Secondly, I chose not to include background/wallpaper in "Load session settings" feature.

The login screen is different from the desktop and has important elements on top of the wallpaper. Those important elements are only tested and designed for the default grey background. When implementing "Load session settings" feature, I tested some images from my collection as GDM backgrounds and only a few of those worked. The rest made the login screen very illegible due to their colors having low contrast with the text color. That made me exclude "background" from the list of settings that get loaded from the session.

Also remember that GDM does not even support changing the background. This app is a hack. [Once GDM supports changing its background](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3877), this feature would become much more useful. Then maybe I'll implement this feature. Right now, I don't want to.

**Comment by IdkWhatToCallMe123** [comment]
>First of all, I think you mean the login screen wallpaper not "lockscreen wallpaper".
>
Ooops you are right Xdd

>Those important elements are only tested and designed for the default grey background. 
>
Fair point. However I do think with [this](https://github.com/gdm-settings/gdm-settings/issues/70) the chances of stuff being illegible are geatly reduced.

The reason I wanted this feature in the first place is because it makes the login process feel a lot smoother, especially when using the Blur My Shell GNOME extension. Instead of just jumping from a gray monotone login screen to being bombarded wit


Example:

![Screenshot from 2023-10-28 15-38-15](https://github.com/gdm-settings/gdm-settings/assets/74187631/a1bc5689-703d-4907-bc44-b68afcb100cf)

![Screenshot from 2023-10-28 15-38-27](https://github.com/gdm-settings/gdm-settings/assets/74187631/aeacb760-bed2-4476-a0da-bc1faa54af59)
