### ISSUE TITLE
support themes located in `.local/share/themes`

### ISSUE THREAD

**Issue by Heus-Sueh** [gdm-settings/gdm-settings#228]
### Description

Apparently, the app cannot use themes that are installed in `.local/share/themes`

### Explanation

I would like to use my themes but gdm settings does not list these themes

**Comment by realmazharhussain** [comment]
GDM runs as the Unix user `gdm` and does not have access to files inside your home directory, including icon, sound, etc. themes installed in your home directory. That is why GDM Settings does not list them.

However, it is currently possible to implement the requested feature for Shell themes, as GDM Settings app copies the chosen shell into `/usr/share/gnome-shell/gnome-shell-theme.gresource` in order to apply it. 

BUT, this is a very dangerous hack, and now that extensions can be enabled in GDM Mode too, the preferred way forward is to not modify a system critical file and instead use the `user-themes` shell extension to load the shell theme. This would make the situation of Shell themes similar to other themes, i.e. not accessible by GDM if they reside in a personal home directory, but it would also make GDM Settings app much safer to use.
