### ISSUE TITLE
Unable to start in Arch Linux with GNOME 46

### ISSUE THREAD

**Issue by Imacolombian346** [gdm-settings/gdm-settings#247]
### What happened?

When i try to run AppImage version i get this error:
Traceback (most recent call last):
  File "/tmp/.mount_GDM_SemHrgAE/usr/bin/gdm-settings", line 12, in <module>
    status = gdms.main()
             ^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/__init__.py", line 86, in main
    from .gui import GdmSettingsApp
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/gui/__init__.py", line 18, in <module>
    from gdms import debug_info
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/debug_info.py", line 14, in <module>
    ("Default GResource File", gresource.get_default()),
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/gresource.py", line 57, in get_default
    if is_unmodified(file):
       ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/gresource.py", line 47, in is_unmodified
    (gresource_contains("gnome-shell.css") or gresource_contains("gnome-shell-dark.css")) and
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/gresource.py", line 44, in <lambda>
    gresource_contains = lambda x: utils.get_stdout(["gresource", "list", gresourceFile, "/org/gnome/shell/theme/" + x])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/site-packages/gdms/utils.py", line 32, in get_stdout
    stdout = subprocess.run(command, stdout=subprocess.PIPE).stdout
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/tmp/.mount_GDM_SemHrgAE/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No existe el fichero o el directorio: 'gresource'

All dependencys are installed:
sudo pacman -S --needed gdm polkit libadwaita glib2 python-gobject gettext
[sudo] password for imacolombian: 
warning: gdm-46.2-1 is up to date -- skipping
warning: polkit-124-2 is up to date -- skipping
warning: libadwaita-1:1.5.1-1 is up to date -- skipping
warning: glib2-2.80.3-2 is up to date -- skipping
warning: python-gobject-3.48.2-1 is up to date -- skipping
warning: gettext-0.22.5-1 is up to date -- skipping
 there is nothing to do

### Expected behavior

The app should start normally without errors, as expected.

### To Reproduce

Install a fresh build of Arch Linux on your PC a | VM (i used `archinstall`), install libfuse2 (`pacman -S libfuse2`) and run the program, as all the dependencies needed comes pre-installed as default.

![Captura desde 2024-06-17 10-12-34](https://github.com/gdm-settings/gdm-settings/assets/97426837/dc1ea102-6eda-40fc-9661-715e520c5598)

_Bug reproduced on a fresh install of Arch Linux, as specified above._

### Application Version

v4.4

### Format/Source

AppImage

### Environment

- **OS**: Arch Linux "Latest" 
- **GNOME**: GNOME 46
- **KERNEL**: 6.9.5-arch1-1

**Comment by Alch-Emi** [comment]
Reporting in with the same bug occurring on NixOS running the flatpak version!  Skimming the source code, it looks like this happens when gdm-settings fails to detect the gnome shell theme gresource.  The process for checking seems to be:

- If `$HOST_DATA_DIRS` is set, parse it as a colon-seperated list of paths and use those, otherwise check `/usr/share` and `/usr/local/share` [[code]](https://github.com/gdm-settings/gdm-settings/blob/8952843fd905005dfe68b86b417532fb0dfce6f2/gdms/env.py#L89C57-L89C72).
- Check each path above for a file called `./gnome-shell/gnome-shell-theme.gresource`. [[code]](https://github.com/gdm-settings/gdm-settings/blob/8952843fd905005dfe68b86b417532fb0dfce6f2/gdms/gresource.py#L18)
- If nothing is found, the internal variable `ShellGresourceFile` is set to `None`, which causes a crash at the location described in the original post.

This means that there's an easy workaround if you can figure out which directory holds the `gnome-shell` config directory and set the `$HOST_DATA_DIRS` environment variable. (at least in theory?  although i couldn't get this to work for me)

For a more permanent solution, it might be worth considering:
- Adding an `else` clause to the for loop from step 2 so that there's a way to show a simple and informational error to the user rather than an opaque crash (or otherwise elegantly handle this case )
- Figuring out if there's a more canonical way to discover the gnome-shell config directory
- Some secret third thing (I'm not really familiar with this code base or with how gnome shell's settings work, so I could easily be misjudging solutions)

**Comment by realmazharhussain** [comment]
1. Does this error occur with the AUR package as well?
2. Does this issue happen after you have launched the app one time, and applied some settings? Or does the app refuse to launch on the first try?

**Comment by Alch-Emi** [comment]
I'm on NixOS, so I can't answer your first question, but as for the second, it happened immediately.  As far as I can tell, there was no difference between the first launch and subsequent launches, and no GUI was ever displayed.  Settings for the app itself should be completely unset or stock.

Checking `~/.var/app/io.github.realmazharhussain.GdmSettings/config`, there's only one file, `monitors.xml`, which is completely empty.  Here's the complete file tree for `~/.var/app/io.github.realmazharhussain.GdmSettings/`:

```
.
├── cache
│   ├── fontconfig
│   └── tmp
├── config
│   └── monitors.xml
└── data
```

**Comment by realmazharhussain** [comment]
Sorry, there was some misunderstanding.

NixOS is currently not supported.

**Comment by realmazharhussain** [comment]
Fixed in Arch Linux.
