### ISSUE TITLE
Shell Theme doesn't completely apply to selection borders

### ISSUE THREAD

**Issue by Bingo90** [gdm-settings/gdm-settings#253]
### What happened?

I'm using the Yaru theme on Fedora. The selection border for the text entry fields isn't using the correct color. Everything else seems to be fine.

Username input field:
![theme3](https://github.com/user-attachments/assets/d17bf679-48e3-463c-8719-a096c5b957fb)
Password input field:
![theme2](https://github.com/user-attachments/assets/e3923e68-a810-48fb-9c23-0f0f63000de5)
Username selection (this works fine):
![theme1](https://github.com/user-attachments/assets/8066fd74-66bb-4d6d-907c-b601672d271c)

### Expected behavior

The border should be orange.

### To Reproduce

The border is blue.

### Application Version

4.4

### Format/Source

Flatpak, Gnome Software, Flathub

### Environment

- **OS**: Fedora 40
- **GNOME**: GNOME Shell 46.3.1

**Comment by Bingo90** [comment]
> This is an issue with the Yaru theme.

Are you sure? It does work in Ubuntu, but installing the Yaru theme from the Fedora repos and copying it from Ubuntu to Fedora both don't work when applied with GDM Settings.

However, I did try it with gdm-extension, link here: https://github.com/PRATAP-KUMAR/gdm-extension
and it worked perfectly fine in Fedora, so I really think this is an issue of GDM Settings not applying the theme correctly.

**Comment by realmazharhussain** [comment]
I don't know how https://github.com/PRATAP-KUMAR/gdm-extension applies user themes but GDM Settings uses the default shell theme as a fallback for styles that are not explicitly declared in th chosen theme. The decision to apply themes that way was made because most shell themes out there are broken/outdated for GDM, and applying them without a fallback, breaks GDM's UI. I'm sure applying Yaru without the default as fallback will work perfectly but we can't change app's behavior for that.
